### ISSUE TITLE
Fix example page.

### ISSUE THREAD

**Issue by elijahcruz12** [ECWebServices/ECKit#2]
Will be working on this including making a navagation bar. Also will be changing the colors.

**Comment by Logan1x** [comment]
Don't know css can i help?@elijahcruz12

**Comment by riktimmondal** [comment]
I would like to work on it.Can you describe more briefly what do i need to do actually?

**Comment by elijahcruz12** [comment]
It just needs to look better than it does currently. I'm talking about the index.html.

@Logan1x of course you can, there are other ways than CSS you can use such as the documentation or the index.html if you know HTML. Also @riktimmondal if you want to fix the page, you can do it to any style of your liking.

**Comment by elijahcruz12** [comment]
@riktimmondal  if you feel like you can create a well page using the current release of ECKit then I will assign you to the task. The colors you choose will go towards a new feature I will be adding using variables. So in other words, have fun, and make it yours!

**Comment by elijahcruz12** [comment]
It is just the index.html in ECKit/ECKit

**Comment by elijahcruz12** [comment]
@riktimmondal are you still interested in doing this?

**Comment by riktimmondal** [comment]
Yes I am interested in this.I am sorry for late replying as exam is going on in my college .I will to submit within this week.

**Comment by elijahcruz12** [comment]
That is fine. I look forward into seeing your PR.

**Comment by alikahwaji** [comment]
@elijahcruz12 can I help with index.html?

**Comment by shivamsaboo17** [comment]
Hi is this issue still open?
Do I have to just make the index.html page look better using CSS?

**Comment by elijahcruz12** [comment]
Hello. This can still be worked on, but currently I will review @alikahwaji PR and go from there. Most likely, if I like it, it will be used and it may be improved on. If not, then there can still be PRs for the example page.

**Comment by elijahcruz12** [comment]
After reviewing, I realized how over board the new version got, so I am gonna restart on the site.

**Comment by shivamsaboo17** [comment]
@elijahcruz12 So is the issue open can I work on index.html?

**Comment by elijahcruz12** [comment]
Yes, you can. I have added the changes that @alikahwaji has added to the index.html.

**Comment by shivamsaboo17** [comment]
Thanks!
Will get back to you by the weekend.

**Comment by elijahcruz12** [comment]
You're welcome. I won't see it until most likely Monday if you send a PR or comment during the weekend itself.

**Comment by shivamsaboo17** [comment]
@elijahcruz12  Well I have been working on index.html and so far been able to do upto this. If you like it I can work on the footer and sidebar within a day or two!

<img width="948" alt="capture1" src="https://user-images.githubusercontent.com/23507911/29786891-775827f8-8c4a-11e7-8764-a5177c29b5ee.PNG">
<img width="948" alt="capture2" src="https://user-images.githubusercontent.com/23507911/29786890-7757928e-8c4a-11e7-8cd4-c8facd00d070.PNG">

**Comment by elijahcruz12** [comment]
I am very impressed! I love forward to seeing this in a PR! Are you compiling the sass then using the already done spaces? Also what column structure are you using? WIth knowing this, I can make this compatible with all 3 versions!

**Comment by shivamsaboo17** [comment]
@elijahcruz12  Thank you!
But I have no idea about SASS and I have used just CSS here. Also please note that the page is not responsive yet.
Actually I saw the index.html in your code and decided to build everything from scratch hence I made it all from scratch using CSS.
I am new to open source hence please tell me how do I merge these separate files into this project.
I have used normal divisions in html and given them inline-block attribute in CSS.

**Comment by elijahcruz12** [comment]
@shivamsaboo17 If you have forked the repository, you can use the documentation [here](https://help.github.com/articles/creating-a-pull-request/) to merge it into the project. If you have not, you must make a fork and copy your code to the fork. Everything you need to know to add your files to the project is essentially [here](https://guides.github.com/activities/forking/). If you have any questions feel free to comment.

**Comment by elijahcruz12** [comment]
If you do not know still how to do this, you can always link the code and I can implement the code. I will still give you credit for sure.

**Comment by shivamsaboo17** [comment]
@elijahcruz12  Thanks, but I got it, was stuck today because I have test tomorrow.
Will put it tomorrow for sure!

**Comment by elijahcruz12** [comment]
@shivamsaboo17 I have merged your PR. This can still be edited, but the issue will be closed as of now.
