### ISSUE TITLE
Doing an ECKit index.html

### ISSUE THREAD

**Issue by elijahcruz12** [ECWebServices/ECKit#9]
Thanks to a PR by @shivamsaboo17 I have a good starting point for doing an index.html, but now, I need to make it actually use ECKit. If anyone is willing to use SCSS and HTML to get my version, indexdev.html to turn into index.html, but use ECKit, I can move faster to updating to the NEW version of ECKit. If you would like to view what they look like, the links are below.

Want to look like: [Here](https://eckit-ecwebservices.c9.io/ECKit/index.html)

Looks like (using ECKit): [Here](https://eckit-ecwebservices.c9.io/ECKit/indexdev.html)

If it does not load for either, please drop a comment and let me know.

**Comment by elijahcruz12** [comment]
Currently for the navbar, the colors are fine, but I would like to fix the navbar from changing lines like such:

![image](https://user-images.githubusercontent.com/14031707/30230257-1dc85b22-94ab-11e7-901e-3de05aa59e1d.png)

another thing is image of the back of the banner is fine, but I would love to make the banner work using ECKit.

**Comment by shivamsaboo17** [comment]
@elijahcruz12 Hi!
I can work upon footer and sidebar and add a few animations if you want, but in css though which you can later translate into sass.
What say?

**Comment by elijahcruz12** [comment]
I would like that, but I would also like someone to code into eckit.

**Comment by shivamsaboo17** [comment]
Hmm as I said before I am not familiar with scss. But atleast if you have a complete model ready it would be easy for somebody to translate it to eckit :)

**Comment by elijahcruz12** [comment]
While it is compiled using scss, the code is pretty much css. It is fine, just as long as the code looks good.

**Comment by elijahcruz12** [comment]
With this noting your last PR, Would it be okay for you to use classes instead of id's? This way I can work faster with the code you are turning in.

**Comment by shivamsaboo17** [comment]
@elijahcruz12 I will do it next week because I am having exams now.
And yes I'll use class this time :)

**Comment by elijahcruz12** [comment]
Thanks for the response. I will be also trying to make a footer as well to go with the design

**Comment by elijahcruz12** [comment]
Thanks for the response. I will be also trying to make a footer as well to go with the design.

**Comment by elijahcruz12** [comment]
This has been finished and the release is done.
